Homework react week#1 Implemented
DiegoRuiz454/hyf-homework pull request #29
Opened 2020-11-19 22:04 UTC by DiegoRuiz454

2020-11-21 14:46 UTC, amerdahabi commented on react/week1/TodoApp.js
> +import ReactDOM from  'react-dom';
we only need ReactDom in our index.js file.

2020-11-21 15:00 UTC, amerdahabi requested changes
Nice work, i left a small notes in your code👍🏻

2020-11-21 15:00 UTC, amerdahabi commented on react/week1/TodoApp.js
> +class TodoList extends React.Component {
for better experience, you can make the TodoList in new component outside App.js , and then import it

2020-11-21 15:00 UTC, amerdahabi commented on react/week1/TodoApp.js
> +    return [<li>{this.props.parameters.render_A} Get out of bed, {this.props.parameters.render_B} "Wed Sep 13 2017"</li>,
to make our code shorter and cleaner i would write this function i n a separate file like so:
```
function TodoList ({params}) {
    return (
         <div>
           <ul>
               {params.map((item)=>{
               return <li key={item.index}>{item.description} ,{item.deadline}</li>
               })}
          </ul>      
        </div>
       )
}

export default TodoList;
```

2020-11-21 15:00 UTC, amerdahabi commented on react/week1/TodoApp.js
> +ReactDOM.render(<Atributes />, document.getElementById('root'));
you can delete this line and the code will keep working, as ReactDom is in the index.js file

2020-11-27 12:53 UTC, DiegoRuiz454 commented on react/week1/TodoApp.js
> +ReactDOM.render(<Atributes />, document.getElementById('root'));
thank you so much for the feedback amerdahabi

2020-11-27 13:04 UTC, merged